[package]
name = "Soccer-Game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aftman = "0.3.0"
wally-package-types = "1.3.1"
