[package]
name = "ulldren/soccer-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7.0"
Observers = "sleitnick/observers@^0.3.4"

Comm = "sleitnick/comm@1.0.1"
Loader = "sleitnick/loader@2.0.0"
Quaternion = "sleitnick/quaternion@0.2.3"
Signal = "sleitnick/signal@^2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
Trove = "sleitnick/trove@1.3.0"

Roact = "roblox/roact@1.4.4"
Promise = "evaera/promise@4.0.0"
SmartBone = "jakeywastaken/smartbone-2@0.4.2"